name: Secure Build and Push

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: helloworld

jobs:
  build-push-secure:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for cosign signing with GitHub OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set tags
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/thestrider/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            docker.io/thestrider/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          provenance: true # Enables SLSA + SBOM

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/thestrider/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: docker.io/thestrider/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          output-file: sbom.spdx.json

      - name: Sign image with Cosign (GitHub OIDC)
        uses: sigstore/cosign-installer@v3
      - name: Cosign sign
        run: |
          cosign sign --yes docker.io/thestrider/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        env:
          COSIGN_EXPERIMENTAL: "1"
